server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://49.254.179.217:8761/eureka

spring:
  application:
    name: api-gateway

token:
  secret: token

logging:
  level:
    root: info
  pattern:
    console: "%green(%date{'yyyy-MM-dd HH:mm:ss','Asia/Seoul'}) %highlight(%-5level) %cyan(%-35logger{5}) %yellow(%3L) %msg %n"